version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: caramelo-db

    restart: always

    environment:
      POSTGRES_USER: caramelo
      POSTGRES_PASSWORD: caramelo123
      POSTGRES_DB: caramelo_store

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: